resources:
  - name: cron_10min
    type: CronTrigger
    configuration:
      interval: "* */10 * * *"

pipelines:
  - name: testing_retention
    configuration:
      retentionPolicy:
        maxAgeDays: 1
        minRuns: 1
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: cron_10min
          integrations:
            - name: git_ben
        execution:
          onExecute:
            - touch sample.txt
            - echo test>sample.txt
            - add_cache_files sample.txt sample
            - add_run_variables sample:$run_id
            - add_pipeline_files sample.txt pipeline_file

      - name: step2
        type: Bash
        configuration:
          inputResources:
            - name: cron_5min
          integrations:
            - name: git_ben
        execution:
         onStart:
           # Restore the file from the previous run of the pipeline
           - restore_pipeline_files pipeline_file sample.txt
           - cat sample.txt
         onExecute:
           echo "Hello world"
