resources:
  - name: cron_10min
    type: CronTrigger
    configuration:
      interval: "*/5 * * * *"

pipelines:
  - name: testing_retention
    configuration:
      retentionPolicy:
        maxAgeDays: 1
        minRuns: 1
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: cron_10min
          integrations:
            - name: ben_git
        execution:
          onExecute:
            - touch sample.txt
            - echo test$run_id>sample.txt
            - add_cache_files sample.txt sample$run_id
            - add_run_variables sample:$run_id
            - add_pipeline_files sample.txt pipeline_file$run_id

      - name: step2
        type: Bash
        configuration:
          inputSteps:
            - name: step1
        execution:
          onStart:
            # Restore the file from the previous run of the pipeline
            - restore_pipeline_files pipeline_file$run_id sample.txt
            - cat sample.txt
          onExecute:
            - echo test>sample.txt
            - add_cache_files sample.txt sample2
            - echo "Hello world"
